import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { Header } from "@/components/Header";
import { Providers } from './providers';
import { Toaster } from "@/components/ui/sonner"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <Providers>
          <div className="flex h-screen flex-col md:flex-row">
            {/* Sidebar collapses on mobile */}
            <aside className="md:block hidden w-full md:w-64 h-auto md:h-screen bg-white border-r shadow-sm">
              <Sidebar />
            </aside>

            {/* Content wrapper */}
            <div className="flex flex-1 flex-col min-h-screen overflow-hidden">
              {/* Sticky header on top */}
              <div className="sticky top-0 z-20 bg-white border-b shadow-sm">
                <Header />
              </div>

              {/* Page content */}
              <main className="flex-1 overflow-y-auto p-4 bg-muted">
                {children}
              </main>
               <Toaster position="top-center" />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
